spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ****
    url: jdbc:mysql://167.99.69.25:3306/test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8091

