spring:
  profiles:
    active: pro
---
spring:
  profiles: dev

server:
  port: 8090
---
spring:
  profiles: pro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://159.203.58.180:3306/dbgirl
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 8080
